SoftBottin/SoftBottin/Controllers/PurchasingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoftBottin.Controllers
{
    public class PurchasingController : UtilitiesController
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult PurchaseSummary()
        {
            return View();
        }
    }
}

SoftBottin/SoftBottin/Controllers/SecurityController.cs
using SoftBottin.Models;
using SoftBottin.Models.Shoes;
using SoftBottinWS;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SoftBottin.Controllers
{
    public class SecurityController : UtilitiesController
    {
        #region Global
        /// <summary>
        /// 
        /// </summary>
        string sErrMsj;
        #endregion


        // GET: Security
        [CompressFilter]
        public ActionResult Principal()
        {

            try
            {
                //cShoeType niShoeType = new cShoeType();
                //cShoe niShoe = new cShoe();
                //DataSet dsShoesTypes = new DataSet();
                //DataSet dsShoe = new DataSet();
                //string sErrMessage = "";
                //niShoeType.GetShoesTypes(out dsShoesTypes, out sErrMessage);
                //niShoe.GetShoes(out dsShoe, out sErrMessage);
                //List<cShoesByType> poShoesByType = new List<cShoesByType>();
                //niShoe.GetShoes(dsShoesTypes, dsShoe, out poShoesByType, out sErrMessage);

                //ViewBag.ShoesByType = poShoesByType;
                //ViewBag.ShoeTypes = dsShoesTypes;
                return View();
            }
            catch (Exception)
            {

                return View();
            }

        }

        [CompressFilter]
        public ActionResult SubPrincipal()
        {

            try
            {
                cShoeType niShoeType = new cShoeType();
                cShoe niShoe = new cShoe();
                DataSet dsShoesTypes = new DataSet();
                DataSet dsShoe = new DataSet();
                string sErrMessage = "";
                niShoeType.GetShoesTypes(out dsShoesTypes, out sErrMessage);
                niShoe.GetShoes(out dsShoe, out sErrMessage);
                List<cShoesByType> poShoesByType = new List<cShoesByType>();
                niShoe.GetShoes(dsShoesTypes, dsShoe, out poShoesByType, out sErrMessage);

                ViewBag.ShoesByType = poShoesByType;
                ViewBag.ShoeTypes = dsShoesTypes;
                return View();
            }
            catch (Exception)
            {

                return View();
            }

        }

        // GET: Security/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Security/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Security/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Security/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Security/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Security/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Security/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        /// <summary>
        /// Daniel Romero 4 de Marzo de 2016
        /// Metodo de tipo post, que se crea para almacenar el correo electronico del cliente
        /// </summary>
        /// <returns></returns>
        [ActionName("AddNewEmailUser")]
        public JsonResult AddNewEmailUser(string sEmail)
        {
            try
            {
                cmSecurity niSecurity = new cmSecurity();
                bool bSuccesfull = true;
                bSuccesfull = niSecurity.AddNewEmailUser(sEmail, out sErrMsj);
                return new JsonResult()
                {
                    Data = bSuccesfull
                };
            }
            catch (Exception ex)
            {
                cUtilities.WriteLog(ex.Message, out sErrMsj);
                return new JsonResult()
                {
                    Data = ex.Message
                };
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="objShoe"></param>
        /// <returns></returns>
        [ActionName("AddNewProduct")]
        public JsonResult AddNewProduct(string objShoe)
        {
            try
            {
                JavaScriptSerializer jss = new JavaScriptSerializer();
                cmProduct user = jss.Deserialize<cmProduct>(objShoe);
                return new JsonResult()
                {
                    Data = true
                };
            }
            catch (Exception ex)
            {
                cUtilities.WriteLog(ex.Message, out sErrMsj);
                return new JsonResult()
                {
                    Data = ex.Message
                };
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [CompressFilter]
        public ActionResult ProductDetail(string sProductReference)
        {
            try
            {
                string sErrMessage = "";
                cmProductDetail niProductDetailt = new cmProductDetail();
                cmProductDetail niProductDetailt2 = new cmProductDetail();
                niProductDetailt.GetFeaturesByShoe(Convert.ToInt32(sProductReference), out niProductDetailt2, out sErrMessage);
                return View(niProductDetailt2);
            }
            catch (Exception)
            {
                return View();
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public JsonResult LogIn(string objUser)
        {
            try
            {
                JavaScriptSerializer jSerializer = new JavaScriptSerializer();
                cmUser user = jSerializer.Deserialize<cmUser>(objUser);
                cmSecurity niSecurity = new cmSecurity();
                DataSet dsUser = new DataSet();
                bool bAccess = niSecurity.LogIn(user.sUserName, user.sPassword, out dsUser, out sErrMsj);
                if (bAccess)
                {
                    Session["userName"] = user.sUserName;
                    Session["RoleID"] = dsUser.Tables[0].Rows[0]["RoleId"].ToString();
                    TempData["userName"] = user.sUserName;
                }


                return new JsonResult() { Data = bAccess };
            }
            catch (Exception)
            {
                return new JsonResult() { };
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="objUser"></param>
        /// <returns></returns>
        public JsonResult SignIn(string objUser)
        {
            try
            {
                Session.Remove("SignIn");
                JavaScriptSerializer jSerializer = new JavaScriptSerializer();
                cmUserSgnIn user = jSerializer.Deserialize<cmUserSgnIn>(objUser);
                cmSecurity niSecurity = new cmSecurity();
                DataSet dsUser = new DataSet();
                bool bAccess = niSecurity.SignIn(user.sFirstName, user.sLastName, user.sEmail, user.sPassword, out sErrMsj);

                if (bAccess)
                {
                    TempData["SignIn"] = true;
                }

                return new JsonResult()
                {
                    Data = bAccess
                };
            }
            catch (Exception)
            {
                return new JsonResult() { };
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult LogOut()
        {
            try
            {
                Session.RemoveAll();
                cShoeType niShoeType = new cShoeType();
                cShoe niShoe = new cShoe();
                DataSet dsShoesTypes = new DataSet();
                DataSet dsShoe = new DataSet();
                string sErrMessage = "";
                niShoeType.GetShoesTypes(out dsShoesTypes, out sErrMessage);
                niShoe.GetShoes(out dsShoe, out sErrMessage);
                List<cShoesByType> poShoesByType = new List<cShoesByType>();
                niShoe.GetShoes(dsShoesTypes, dsShoe, out poShoesByType, out sErrMessage);

                ViewBag.ShoesByType = poShoesByType;
                ViewBag.ShoeTypes = dsShoesTypes;
                return View("Principal");
            }
            catch (Exception)
            {
                return View("Principal");
            }
        }


        /// <summary>
        /// Daniel Romero 26 de Junio de 2016
        /// Metodo que permite verificar la existencia de un email repetido
        /// </summary>
        /// <param name="sEmail"></param>
        /// <returns></returns>
        public JsonResult CheckEmail(string sEmail)
        {
            try
            {

                cmSecurity niSecurity = new cmSecurity();
                DataSet dsUser = new DataSet();
                bool bAccess = niSecurity.CheckEmail(sEmail, out dsUser, out sErrMsj);


                if (dsUser.Tables.Count > 0)
                {
                    if (dsUser.Tables[0].Rows.Count > 0)
                    {

SoftBottin/SoftBottin/Views/Purchasing/PurchaseSummary.cshtml
@{
    Layout = null;
}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Principal</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link href="@Url.Content("~/Content/Boostrap/bootstrap.min.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Content/Boostrap/bootstrap-theme.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Boostrap/main.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/Boostrap/Vendor/modernizr-2.8.3-respond-1.4.2.min.js")"></script>
    <link rel="stylesheet" href="@Url.Content("~/Content/Icomoon/style.css")">
</head>
<body>

    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->


    <header class="app-header">
        <nav class="navbar app-navbar navbar-fixed-top">
            <div class="container ">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                        <span class="icon-bar app-icon"></span>
                        <span class="icon-bar app-icon"></span>
                        <span class="icon-bar app-icon"></span>
                    </button>
                    @Html.ActionLink("Bottini Calzado Accesorios", "Principal", "Security", new { }, new { @class = "navbar-brand app-link" })
                </div>
                <div class="collapse navbar-collapse" id="menu">
                    <ul class="nav navbar-nav navbar-right app-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Ultimas Colecciones 2016<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Tacones Abril 2016</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Botas Abril 2016</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Estilo Militar Abril 2016</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="" data-toggle="modal" data-target="#mdlogIn">
                                Ingresa
                            </a>
                        </li>
                        <li>
                            <a href="" data-toggle="modal" data-target="#mdSignIn">
                                Registrate
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="navbar-fixed-top  app-shopping-cart-container">
            <div class="row " id="divShoppingCard">
                <div class="col-md-1 col-md-offset-11" id="divShoppingCardSee">
                    <div class="well pull-right">
                        <span class="glyphicon glyphicon-shopping-cart app-glyphicon4" style="margin-top:1%" id="numberShoesPick">0</span>
                        <br />
                        <h4 class="app-letra">Detalle</h4>
                    </div>
                </div>
                <div class="col-md-5 col-md-offset-7" style="display:none" id="divShoppingCardDetail">
                    <div class="well pull-right">
                        <button type="button" class="close" id="btCloseShoppingCard">&times;</button>
                        <table class="table table-bordered" id="tbShoppingCardDetail">
                            <thead>
                                <tr>
                                    <th class="hidden-xs"></th>
                                    <th class="hidden-xs">Foto</th>
                                    <th>Nombre</th>
                                    <th class="hidden-xs">Cantidad</th>
                                    <th>Precio</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <td>Total</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>$0.0</td>
                                </tr>
                            </tfoot>
                            <tbody>
                                @*<tr>
                                        <th scope="row">1</th>
                                        <td>
                                            <img src="@Url.Content("~/Content/Images/Militar/Zapato10.jpg")" class="img-circle img-responsive" width="25" height="25" />
                                        </td>
                                        <td>
                                            Militar 15
                                        </td>
                                        <td>
                                            1
                                        </td>
                                        <td>
                                            $120.000
                                        </td>

                                    </tr>*@
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center navbar-fixed-top" style="margin-top: 4.5%">
                <div class="alert alert-success " style="display:none;" role="alert" id="altSuccess">
                    @*<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>*@
                    <strong>Holy guacamole!</strong> You should check in on some of those fields below.
                </div>
            </div>
        </div>

    </header>

    <section class="app-seccion1-purchase-summary">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h1 class="text-center">Resumen de Compra</h1>
                @*<table class="table table-bordered table-hover" id=" tbshoppingcarddetail">*@
                <table id="example" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0">
                    <thead>
                        <tr>
                            <th class="hidden-xs"></th>
                            <th class="hidden-xs">Foto</th>
                            <th>Nombre</th>
                            <th class="hidden-xs">Cantidad</th>
                            <th class="hidden-xs">Color</th>
                            <th class="hidden-xs">Talla</th>
                            <th>Precio</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td>Total</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>$270,000.0</td>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>
                                <img src="@Url.Content("~/Content/Images/Militar/Zapato11.jpg")" class="img-circle img-responsive" width="25" height="25" />
                            </td>
                            <td>
                                Militar 15
                            </td>
                            <td>
                                1
                            </td>
                            <td>
                                Amarillo
                            </td>
                            <td>
                                36
                            </td>
                            <td>
                                $120,000
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>
                                <img src="@Url.Content("~/Content/Images/Militar/Zapato10.jpg")" class="img-circle img-responsive" width="25" height="25" />
                            </td>
                            <td>
                                Tacon Charol
                            </td>
                            <td>
                                2
                            </td>
                            <td>
                                Negro
                            </td>
                            <td>
                                37
                            </td>
                            <td>
                                $150,000
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <button class="btn btn-block btn-danger">Cancelar</button>
            </div>
            <div class="col-md-6">
                <button class="btn btn-block btn-success">Comprar</button>
            </div>
        </div>

    </section>


    <link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
    <script src="//cdn.datatables.net/responsive/2.0.2/js/dataTables.responsive.min.js"></script>
    <script src="//cdn.datatables.net/responsive/2.0.2/js/responsive.bootstrap.min.js"></script>

    <script>window.jQuery || document.write('<script src="@Url.Content("~/Scripts/Boostrap/Vendor/jquery-1.11.2.js")"><\/script>')</script>
    <script>window.jQuery || document.write('<script src="@Url.Content("~/Scripts/GoogleApis/.js")"><\/script>')</script>
    <script src="@Url.Content("~/Scripts/Boostrap/Vendor/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Boostrap/plugins.js")"></script>
    <script src="@Url.Content("~/Scripts/Boostrap/main.js")"></script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function (b, o, i, l, e, r) {
            b.GoogleAnalyticsObject = l; b[l] || (b[l] =
            function () { (b[l].q = b[l].q || []).push(arguments) }); b[l].l = +new Date;
            e = o.createElement(i); r = o.getElementsByTagName(i)[0];
            e.src = '//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e, r)
        }(window, document, 'script', 'ga'));
        ga('create', 'UA-34048295-4', 'auto'); ga('send', 'pageview');
    </script>
    <script type="text/javascript">
        window.rootUrl = '@Url.Content("~/")';

        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>

</body>
</html>