SoftBottin/SoftBottin/Controllers/PurchasingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoftBottin.Controllers
{
    public class PurchasingController : UtilitiesController
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult PurchaseSummary()
        {
            return View();
        }
    }
}

SoftBottin/SoftBottin/Controllers/SecurityController.cs
using SoftBottin.Models;
using SoftBottin.Models.Shoes;
using SoftBottinWS;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SoftBottin.Controllers
{
    public class SecurityController : UtilitiesController
    {
        #region Global
        /// <summary>
        /// 
        /// </summary>
        string sErrMsj;
        #endregion


        // GET: Security
        [CompressFilter]
        public ActionResult Principal()
        {

            try
            {
                //cShoeType niShoeType = new cShoeType();
                //cShoe niShoe = new cShoe();
                //DataSet dsShoesTypes = new DataSet();
                //DataSet dsShoe = new DataSet();
                //string sErrMessage = "";
                //niShoeType.GetShoesTypes(out dsShoesTypes, out sErrMessage);
                //niShoe.GetShoes(out dsShoe, out sErrMessage);
                //List<cShoesByType> poShoesByType = new List<cShoesByType>();
                //niShoe.GetShoes(dsShoesTypes, dsShoe, out poShoesByType, out sErrMessage);

                //ViewBag.ShoesByType = poShoesByType;
                //ViewBag.ShoeTypes = dsShoesTypes;
                return View();
            }
            catch (Exception)
            {

                return View();
            }

        }

        [CompressFilter]
        public ActionResult SubPrincipal()
        {

            try
            {
                cShoeType niShoeType = new cShoeType();
                cShoe niShoe = new cShoe();
                DataSet dsShoesTypes = new DataSet();
                DataSet dsShoe = new DataSet();
                string sErrMessage = "";
                niShoeType.GetShoesTypes(out dsShoesTypes, out sErrMessage);
                niShoe.GetShoes(out dsShoe, out sErrMessage);
                List<cShoesByType> poShoesByType = new List<cShoesByType>();
                niShoe.GetShoes(dsShoesTypes, dsShoe, out poShoesByType, out sErrMessage);

                ViewBag.ShoesByType = poShoesByType;
                ViewBag.ShoeTypes = dsShoesTypes;
                return View();
            }
            catch (Exception)
            {

                return View();
            }

        }

        // GET: Security/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Security/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Security/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Security/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Security/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Security/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Security/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        /// <summary>
        /// Daniel Romero 4 de Marzo de 2016
        /// Metodo de tipo post, que se crea para almacenar el correo electronico del cliente
        /// </summary>
        /// <returns></returns>
        [ActionName("AddNewEmailUser")]
        public JsonResult AddNewEmailUser(string sEmail)
        {
            try
            {
                cmSecurity niSecurity = new cmSecurity();
                bool bSuccesfull = true;
                bSuccesfull = niSecurity.AddNewEmailUser(sEmail, out sErrMsj);
                return new JsonResult()
                {
                    Data = bSuccesfull
                };
            }
            catch (Exception ex)
            {
                cUtilities.WriteLog(ex.Message, out sErrMsj);
                return new JsonResult()
                {
                    Data = ex.Message
                };
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="objShoe"></param>
        /// <returns></returns>
        [ActionName("AddNewProduct")]
        public JsonResult AddNewProduct(string objShoe)
        {
            try
            {
                JavaScriptSerializer jss = new JavaScriptSerializer();
                cmProduct user = jss.Deserialize<cmProduct>(objShoe);
                return new JsonResult()
                {
                    Data = true
                };
            }
            catch (Exception ex)
            {
                cUtilities.WriteLog(ex.Message, out sErrMsj);
                return new JsonResult()
                {
                    Data = ex.Message
                };
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [CompressFilter]
        public ActionResult ProductDetail(string sProductReference)
        {
            try
            {
                string sErrMessage = "";
                cmProductDetail niProductDetailt = new cmProductDetail();
                cmProductDetail niProductDetailt2 = new cmProductDetail();
                niProductDetailt.GetFeaturesByShoe(Convert.ToInt32(sProductReference), out niProductDetailt2, out sErrMessage);
                return View(niProductDetailt2);
            }
            catch (Exception)
            {
                return View();
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public JsonResult LogIn(string objUser)
        {
            try
            {
                JavaScriptSerializer jSerializer = new JavaScriptSerializer();
                cmUser user = jSerializer.Deserialize<cmUser>(objUser);
                cmSecurity niSecurity = new cmSecurity();
                DataSet dsUser = new DataSet();
                bool bAccess = niSecurity.LogIn(user.sUserName, user.sPassword, out dsUser, out sErrMsj);
                if (bAccess)
                {
                    Session["userName"] = user.sUserName;
                    Session["RoleID"] = dsUser.Tables[0].Rows[0]["RoleId"].ToString();
                    TempData["userName"] = user.sUserName;
                }


                return new JsonResult() { Data = bAccess };
            }
            catch (Exception)
            {
                return new JsonResult() { };
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="objUser"></param>
        /// <returns></returns>
        public JsonResult SignIn(string objUser)
        {
            try
            {
                Session.Remove("SignIn");
                JavaScriptSerializer jSerializer = new JavaScriptSerializer();
                cmUserSgnIn user = jSerializer.Deserialize<cmUserSgnIn>(objUser);
                cmSecurity niSecurity = new cmSecurity();
                DataSet dsUser = new DataSet();
                bool bAccess = niSecurity.SignIn(user.sFirstName, user.sLastName, user.sEmail, user.sPassword, out sErrMsj);

                if (bAccess)
                {
                    TempData["SignIn"] = true;
                }

                return new JsonResult()
                {
                    Data = bAccess
                };
            }
            catch (Exception)
            {
                return new JsonResult() { };
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult LogOut()
        {
            try
            {
                Session.RemoveAll();
                cShoeType niShoeType = new cShoeType();
                cShoe niShoe = new cShoe();
                DataSet dsShoesTypes = new DataSet();
                DataSet dsShoe = new DataSet();
                string sErrMessage = "";
                niShoeType.GetShoesTypes(out dsShoesTypes, out sErrMessage);
                niShoe.GetShoes(out dsShoe, out sErrMessage);
                List<cShoesByType> poShoesByType = new List<cShoesByType>();
                niShoe.GetShoes(dsShoesTypes, dsShoe, out poShoesByType, out sErrMessage);

                ViewBag.ShoesByType = poShoesByType;
                ViewBag.ShoeTypes = dsShoesTypes;
                return View("Principal");
            }
            catch (Exception)
            {
                return View("Principal");
            }
        }


        /// <summary>
        /// Daniel Romero 26 de Junio de 2016
        /// Metodo que permite verificar la existencia de un email repetido
        /// </summary>
        /// <param name="sEmail"></param>
        /// <returns></returns>
        public JsonResult CheckEmail(string sEmail)
        {
            try
            {

                cmSecurity niSecurity = new cmSecurity();
                DataSet dsUser = new DataSet();
                bool bAccess = niSecurity.CheckEmail(sEmail, out dsUser, out sErrMsj);


                if (dsUser.Tables.Count > 0)
                {
                    if (dsUser.Tables[0].Rows.Count > 0)
                    {

SoftBottin/SoftBottin/Views/Security/Confirmation.cshtml
@{
    ViewBag.Title = "Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirmation</h2>

SoftBottin/SoftBottin/Views/Security/Principal.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    System.Data.DataSet dsResult = (System.Data.DataSet)ViewBag.ShoeTypes;
    List<SoftBottin.Models.Shoes.cShoesByType> poShoesByType = (List<SoftBottin.Models.Shoes.cShoesByType>)ViewBag.ShoesByType;
}

<style>
    #loading {
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        position: fixed;
        display: block;
        opacity: 0.7;
        background-color: #fff;
        z-index: 99;
        text-align: center;
    }

    #loading-image {
        position: absolute;
        /*top: 50%;*/
        /*left: 40%;*/
        z-index: 100;
        /*text-align: center;*/
        top: 50%;
        left: 50%;
        margin-right: -50%;
        transform: translate(-50%, -50%);
    }
</style>

<div id="loading" ng-hide="!layout.loading">
    <img id="loading-image" src="@Url.Content("~/Content/Images/ring.gif")" width="100" />
</div>


<script src="http://maps.google.com/maps/api/js?sensor=false&key=AIzaSyBiRCM_Mengpbc_KBtNp4BspRpQLD2N554"></script>

<script>


    $(document).ready(function () {
        var var_map;

        function init_map() {
            var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
            var labelIndex = 0;

            //Cl. 9 #21-3, Bogotá, Colombia
            var var_location = new google.maps.LatLng(4.604770, -74.089588);
            //carrrera22 #8-92
            var var_location2 = new google.maps.LatLng(4.605194, -74.090190);
            //calle 9 #22-30
            var var_location3 = new google.maps.LatLng(4.605365, -74.090334);

            var var_mapoptions = {
                center: var_location,
                zoom: 17
            };



            var_map = new google.maps.Map(document.getElementById("map-container"), var_mapoptions);

            var var_marker = new google.maps.Marker({
                position: var_location,
                map: var_map,
                label: labels[labelIndex++ % labels.length],
                title: "Venice"
            });

            var var_marker2 = new google.maps.Marker({
                position: var_location2,
                map: var_map,
                label: labels[labelIndex++ % labels.length],
                title: "Venice"
            });

            var var_marker3 = new google.maps.Marker({
                position: var_location3,
                map: var_map,
                label: labels[labelIndex++ % labels.length],
                title: "Venice"
            });
            var_marker.setMap(var_map);


            google.maps.event.trigger(var_map, 'resize');
        }

        google.maps.event.addDomListener(window, 'load', init_map);

    });

</script>




<div ng-controller="carritoController" ng-show="!layout.loading">
    <resolve-loader></resolve-loader>
    <div ng-view>
        @Html.Partial("SubPrincipal")
    </div>
</div>


<section class="app-seccion2">
    <div class="container">
        <div class="row">
            <div class="col-xs-12xol "></div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h1 class="app-titulo"><span class="app-resaltar">Acerca de Nostros</span> </h1>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                    <div class="media app-media">
                        <div class="pull-left">
                            <span class="glyphicon glyphicon-time app-glyphicon1"></span>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">
                                Contáctanos
                            </h4>
                            <p class="app-justificar2">
                                Llámanos o escríbenos, y tendrás respuesta en tiempo record.
                                <span class="pull-right glyphicon glyphicon-time"></span>
                                Tenemos a tú disposición: whatsapp, facebook,telefono celular, correo electrónico.
                            </p>
                        </div>
                    </div>

                    <div class="media app-media">
                        <div class="pull-left">
                            <span class="glyphicon glyphicon-refresh app-glyphicon1"></span>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">
                                Entendemos que tú eres la mayor prioridad
                            </h4>
                            <p class="app-justificar2">
                                Estaremos siempre dispuestos hasta que quedes satisfecho.
                                <span class="pull-right glyphicon glyphicon-thumbs-up"></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">



            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h1 class="app-titulo"><span class="app-resaltar">¿Dónde nos encuentras?</span> </h1>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

                        <div class="card">
                            <div class="card-height-indicator"></div>
                            <div class="card-content">
                                <div class="media app-media" style="margin-top: 3em;">
                                    <div class="pull-left">
                                        <span class="glyphicon  glyphicon glyphicon-map-marker app-glyphicon1"></span>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading" style="padding: 1em;">
                                            Bottini A
                                        </h4>
                                        <p class="app-justificar2">
                                            <address>
                                                San Andresito, San Jose<br>
                                                Calle 9 #21-03<br>
                                                Bogóta<br>
                                                Colombia<br>
                                                <abbr>P:</abbr> +57 321 528 3546
                                            </address>
                                        </p>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 row-centered">
                                    <a target="_blank" class="btn btn-warning btn-lg" href="https://maps.google.com?saddr=Current+Location&daddr=4.604762,-74.089582">Ir a Bottini A</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                        <div class="card">
                            <div class="card-height-indicator"></div>
                            <div class="card-content">
                                <div class="media app-media" style="margin-top: 3em;">
                                    <div class="pull-left">
                                        <span class="glyphicon  glyphicon glyphicon-map-marker app-glyphicon1"></span>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading" style="padding: 1em;">
                                            Bottini B
                                        </h4>
                                        <p class="app-justificar2">
                                            <address>
                                                San Andresito, San Jose<br>
                                                Carrera 22 #8-92<br>
                                                Bogóta<br>
                                                Colombia<br>
                                                <abbr>P:</abbr> +57 321 528 3546
                                            </address>
                                        </p>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 row-centered">
                                    <a target="_blank" class="btn btn-warning btn-lg" href="https://maps.google.com?saddr=Current+Location&daddr=4.605167,-74.090185">Ir a Bottini B</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

                        <div class="card">
                            <div class="card-height-indicator"></div>
                            <div class="card-content">

                                <div class="media app-media" style="margin-top: 3em;">
                                    <div class="pull-left">
                                        <span class="glyphicon  glyphicon glyphicon-map-marker app-glyphicon1"></span>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading" style="padding: 1em;">
                                            Bottini C
                                        </h4>
                                        <p class="app-justificar2">
                                            <address>
                                                San Andresito, San Jose<br>
                                                Calle 9 #22-30<br>
                                                Bogóta<br>
                                                Colombia<br>
                                                <abbr>P:</abbr> +57 321 528 3546
                                            </address>
                                        </p>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 row-centered">
                                    <a target="_blank" class="btn btn-warning btn-lg" href="https://maps.google.com?saddr=Current+Location&daddr=4.605390,-74.090331">Ir a Bottini C</a>
                                    
                                </div>
                            </div>
                        </div>
                    </div>


                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding-top: 2em;">

                    <div class="card">
                        <div class="card-height-indicator"></div>
                        <div class="card-content">
                            <div id="map-container" class="col-md-8"></div>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
</section>


@Html.Hidden("RedirectTo", Url.Action("PurchaseSummary", "Purchasing"))

SoftBottin/SoftBottin/Views/Security/Response.cshtml
@{
    ViewBag.Title = "Response";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container"> 
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>Transaccion finalizada!</strong> Ahora tus zapatos estan en camino
        <a href="javascript:void(0)" class="alert-link">Gracias por tu confianza</a>.
    </div>   
    <div class="row">
        <div class="jumbotron">
            <h1 class="center-block text-center">Respuesta</h1>

            <p>
                @Request.Params["merchantId"]
                <br />
                @Request.Params["merchant_name"]
                <br />
                @Request.Params["merchant_address"]
                <br />
                @Request.Params["telephone"]
                <br />
                @Request.Params["merchant_url"]
                <br />
                @Request.Params["transactionState"]
                <br />
                @Request.Params["lapTransactionState"]
                <br />
                @Request.Params["message"]
                <br />
                @Request.Params["referenceCode"]
                <br />
                @Request.Params["transactionId"]
                <br />
                @Request.Params["description"]
                <br />
                @Request.Params["polTransactionState"]
                <br />
                @Request.Params["signature"]
                <br />
                @Request.Params["polResponseCode"]
                <br />
                @Request.Params["polPaymentMethod"]
                <br />
                @Request.Params["lapPaymentMethod"]
                <br />
                @Request.Params["polPaymentMethodType"]
                <br />
                @Request.Params["lapPaymentMethodType"]
                <br />
                @Request.Params["processingDate"]
                <br />
            </p>

            <p><a class="btn btn-primary btn-lg">Aceptar</a></p>
        </div>
    </div>
</div>

SoftBottin/SoftBottin/Views/Security/ViewShoppingCart.cshtml
<div class="container" style="margin-top: 5em;">
    <div class="row">
        <div class="jumbotron">
            <div ng-controller="ShoppingCartCtrl">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                            <strong>Tu carrito</strong><br>
                            <h5><small>{{getTotalShopping()}} (ZAPATOS)</small></h5>
                        </div>
                    </div>
                    <blockquote>
                        <div class="row" ng-repeat="actividad in shoe">

                            <div class="col-xs-4 col-sm-1 col-md-1 col-lg-1 app-shoppingCart-img">
                                <img src="{{actividad.imageShoe}}" width="72" height="72" />
                            </div>
                            <div class="col-xs-7 col-sm-2 col-md-3 col-lg-3 app-shoppingCart app-shoppingCart-first-el app-view-shopping-cart">
                                <strong>
                                    {{actividad.name}}
                                </strong>
                            </div>
                            <div class="col-xs-7 col-sm-2 col-md-2 col-lg-2 app-shoppingCart app-view-shopping-cart">
                                <span>Ctd:</span>
                                {{actividad.quantity}}
                            </div>
                            <div class="col-xs-7 col-sm-2 col-md-2 col-lg-2 app-shoppingCart app-view-shopping-cart">
                                <span>
                                    Talla:
                                </span>
                                {{actividad.size}}
                            </div>
                            <div class="col-xs-7 col-sm-2 col-md-2 col-lg-2 app-shoppingCart app-view-shopping-cart">
                                ${{actividad.price | number:2}}
                            </div>
                            <div class="col-xs-7 col-sm-2 col-md-2 col-lg-2  text-right app-shoppingCart app-view-shopping-cart">
                                <span class="glyphicon glyphicon glyphicon-remove text-right" ng-click="removeActv(actividad)"></span>
                            </div>
                        </div>
                    </blockquote>
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="pull-right right">
                                <h4>
                                    TOTAL A PAGAR:
                                    <span class="label label-default">${{getTotal() | number:2}}</span>
                                </h4>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="pull-right right">
                                <a href="#CheckOut">
                                    <span class="glyphicon glyphicon-saved app-glyphicon2 add-to-cart">
                                        VERIFICAR
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>


                @*<div class="container" style="padding-top:5em;">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <a class="glyphicon glyphicon glyphicon-arrow-left app-link" style="padding: 1em;" href="#/">
                            Volver
                        </a>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-responsive table-bordered">
                            <thead>
                                <tr class="info">
                                    <th>Nombre</th>
                                    <th>Talla</th>
                                    <th>Cantidad</th>
                                    <th>Precio (Unidad)</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="actividad in shoe">
                                    <td>{{actividad.name}}</td>
                                    <td>{{actividad.size}}</td>
                                    <td>{{actividad.quantity}}</td>
                                    <td>${{actividad.price | number:2}}</td>
                                    <td>
                                        <span class="glyphicon glyphicon glyphicon-remove text-right" ng-click="removeActv(actividad)"></span>
                                    </td>
                                </tr>
                                <tr class="success">
                                    <td>Total </td>
                                    <td>&nbsp;</td>
                                    <td scope="row">{{getTotalShopping()}}</td>
                                    <td scope="row">${{getTotal() | number:2}}</td>
                                    <td scope="row"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="pull-right right">
                            <h4>
                                TOTAL A PAGAR:
                                <span class="label label-default">${{getTotal() | number:2}}</span>
                            </h4>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="pull-right right">
                            <a href="#CheckOut">
                                <span class="glyphicon glyphicon glyphicon-saved app-glyphicon2 add-to-cart">
                                    VERIFICAR
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>*@
            </div>
        </div>
    </div>
</div>